spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  kafka:
    listener:
      auto-startup: false
    consumer:
      auto-offset-reset: earliest
    producer:
      properties:
        max.block.ms: 250

tradex:
  risk:
    max-order-value: 100000.0000
    max-order-quantity: 10000
    max-daily-trading-value: 500000.0000
  withdrawal:
    minimum-amount: 10.0000
    maximum-amount: 50000.0000
    daily-limit: 100000.0000
    monthly-limit: 500000.0000
