package com.tradex.event.model;

public enum EventType {
    ORDER_CREATED,
    ORDER_CANCELLED,
    ORDER_PARTIALLY_FILLED,
    ORDER_FILLED,
    TRADE_EXECUTED,
    DEPOSIT_COMPLETED,
    BUY_SETTLEMENT_COMPLETED,
    SELL_SETTLEMENT_COMPLETED,
    RISK_ORDER_REJECTED,
    KYC_SUBMITTED,
    KYC_VERIFIED,
    KYC_REJECTED,
    AML_REVIEW_REQUIRED,
    AML_BLOCKED,
    WITHDRAWAL_REQUESTED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,
    WITHDRAWAL_COMPLETED,
    WITHDRAWAL_FAILED
}
